/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelbooking;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Kushagra Srivastava
 */
public class BookingConfirmation extends javax.swing.JFrame {
    
    
        
    String username;
    int refno;
    String HotelName;
    int nor;
    java.sql.Date sqlFromDate;
    java.sql.Date sqlToDate;
    int status;
    int totalprice;

    /**
     * Creates new form BookingConfirmation
     */
    public BookingConfirmation(int refNo, String user, String hotelname, int noofrooms, java.sql.Date fromdate , java.sql.Date todate, int Status, int price) {
        setContentPane(new JLabel(new ImageIcon("D:\\\\JOOPS\\\\HotelBooking\\\\src\\\\hotelbooking\\\\bg1.jpg")));
        initComponents();
        
        bmt.setBorder(null);
        bmt.setBorderPainted(false);
        bmt.setContentAreaFilled(false);
        bmt.setOpaque(false);
        
        invalid_id.setVisible(false);
        message1.setVisible(false);
        message2.setVisible(false);
        ref_message.setVisible(false);
        
        select_id.add(aadhar);
        select_id.add(pan);

        
        username=user;
        refno = refNo;
        HotelName = hotelname;
        nor = noofrooms;
        sqlFromDate = fromdate;
        sqlToDate = todate;
        status = Status;
        totalprice = price;
        
        hello.setText("Hello "+username+" !");
        
    }

    boolean checkAadhar(String uid) {
        
        boolean not_number=true;
        
        for(int i=0;i<uid.length();i++)
        {
            if(!(uid.charAt(i)>='0' && uid.charAt(i)<='9'))
                return false;
        }
        
        if(uid.length()!=12)
            return false;
        
        return true;
    }
    
    boolean checkPan(String uid) {
        if(uid.length()!=10)
            return false;
        
        for(int i=0;i<5;i++)
        {
            if(!(uid.charAt(i)>='A' && uid.charAt(i)<='Z'))
                return false;
        }
        
        for(int i=5;i<9;i++)
        {
            if(!(uid.charAt(i)>='0' && uid.charAt(i)<='9'))
                return false;
        }
        
        if(!(uid.charAt(9)>='A' && uid.charAt(9)<='Z'))
                return false;
        
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        select_id = new javax.swing.ButtonGroup();
        idno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aadhar = new javax.swing.JRadioButton();
        pan = new javax.swing.JRadioButton();
        confirm = new javax.swing.JButton();
        invalid_id = new javax.swing.JLabel();
        hello = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        message1 = new javax.swing.JLabel();
        message2 = new javax.swing.JLabel();
        ref_message = new javax.swing.JLabel();
        bmt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        idno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnoActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Type");

        jLabel2.setText("ID Number");

        aadhar.setText("Aadhar");

        pan.setText("PAN");
        pan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panActionPerformed(evt);
            }
        });

        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        invalid_id.setForeground(new java.awt.Color(255, 51, 51));
        invalid_id.setText("Enter valid ID number");

        hello.setFont(new java.awt.Font("Georgia", 2, 20)); // NOI18N
        hello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hello.setText("Hello User!");

        jButton1.setText("Go back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        message1.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        message1.setForeground(new java.awt.Color(51, 255, 0));
        message1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message1.setText("Your booking is succesful!");

        message2.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        message2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message2.setText("Booking Reference Number");

        ref_message.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ref_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ref_message.setText("0000");

        bmt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbooking/bmtlogo.png"))); // NOI18N
        bmt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bmt.setBorderPainted(false);
        bmt.setOpaque(false);
        bmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(79, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idno)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aadhar)
                                .addGap(101, 101, 101)
                                .addComponent(pan))
                            .addComponent(invalid_id, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                        .addGap(0, 236, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bmt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 537, Short.MAX_VALUE)
                        .addComponent(hello, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(message1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(message2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(ref_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(467, 467, 467))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(hello, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bmt)))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aadhar)
                    .addComponent(pan))
                .addGap(20, 20, 20)
                .addComponent(invalid_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(confirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(message1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ref_message, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void storeBooking(){
        message1.setVisible(true);
        message2.setVisible(true);
        ref_message.setVisible(true);
        confirm.setVisible(false);
        ref_message.setText(Integer.toString(refno));
        
        Connection myconn = null;
        try{
            myconn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels", "root", "n!gg3|2f@gg0t"); 
            String sql = "insert into bookings(RefNo, Username, HotelName, NoOfRooms,FromDate , ToDate, Status, Price) values (?,?,?,?,?,?,?,?)";
            PreparedStatement statement = myconn.prepareStatement(sql);
            statement.setInt(1, refno);
            statement.setString(2, username);
            statement.setString(3, HotelName);
            statement.setInt(4, nor);             //CONFIRM EVENT HANDLING
            statement.setDate(5, sqlFromDate);
            statement.setDate(6, sqlToDate);
            statement.setInt(7, status);
            statement.setInt(8, totalprice);
            System.out.println(statement);
            statement.executeUpdate();
        }
        catch(Exception e){
            System.out.println("xxxxxxxxxxxxxx");
            System.out.println(e);
        }
    }
    private void panActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panActionPerformed

    private void idnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnoActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        if(select_id.isSelected(aadhar.getModel())) {
        
            if(checkAadhar(idno.getText())==false) {
                invalid_id.setText("Enter valid Aadhar number");
                invalid_id.setVisible(true);
            }

            else {
                invalid_id.setVisible(false);
                storeBooking();
            }
        }
        
        else if(select_id.isSelected(pan.getModel())) {
            if(checkPan(idno.getText())==false) {
                invalid_id.setText("Enter valid PAN number");
                invalid_id.setVisible(true);
            }

            else {
                invalid_id.setVisible(false);
                storeBooking();
            }
        }
    }//GEN-LAST:event_confirmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BookingConfirmation.this.setVisible(false);
        EnterInfoScreen eis = new EnterInfoScreen(username);
        eis.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmtActionPerformed
        // TODO add your handling code here:
        BookingConfirmation.this.setVisible(false);

        HomePage hp = new HomePage();
        hp.setVisible(true);
    }//GEN-LAST:event_bmtActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aadhar;
    private javax.swing.JButton bmt;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel hello;
    private javax.swing.JTextField idno;
    private javax.swing.JLabel invalid_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel message1;
    private javax.swing.JLabel message2;
    private javax.swing.JRadioButton pan;
    private javax.swing.JLabel ref_message;
    private javax.swing.ButtonGroup select_id;
    // End of variables declaration//GEN-END:variables
}
