/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelbooking;

import javax.swing.ImageIcon;
import javax.swing.JLabel;


/**
 *
 * @author hp
 */
public class OptionSelection extends javax.swing.JFrame {

    /**
     * Creates new form OptionSelection
     */
    String user;
    public OptionSelection(String User) {
        setContentPane(new JLabel(new ImageIcon("D:\\\\JOOPS\\\\HotelBooking\\\\src\\\\hotelbooking\\\\bg1.jpg")));
        initComponents();
        
        bmt.setBorder(null);
        bmt.setBorderPainted(false);
        bmt.setContentAreaFilled(false);
        bmt.setOpaque(false);
        
        
        user=User;
        hello.setText("Hello " + user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hello = new javax.swing.JLabel();
        newbooking = new javax.swing.JButton();
        viewbookings = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bmt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        hello.setFont(new java.awt.Font("Georgia", 2, 20)); // NOI18N
        hello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hello.setText("Hello User!");

        newbooking.setText("New Booking");
        newbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbookingActionPerformed(evt);
            }
        });

        viewbookings.setText("View Bookings");
        viewbookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbookingsActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bmt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbooking/bmtlogo.png"))); // NOI18N
        bmt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bmt.setBorderPainted(false);
        bmt.setOpaque(false);
        bmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bmt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hello, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 492, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(viewbookings, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newbooking, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(498, 498, 498))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(84, 84, 84))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hello, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(114, 114, 114)
                .addComponent(newbooking, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(viewbookings, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbookingActionPerformed
        // TODO add your handling code here:
        EnterInfoScreen EIS = new EnterInfoScreen(user);
        EIS.setVisible(true);
        OptionSelection.this.setVisible(false);
    }//GEN-LAST:event_newbookingActionPerformed

    private void viewbookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbookingsActionPerformed
        // TODO add your handling code here:
        ViewBookings VB = new ViewBookings(user);
        VB.setVisible(true);
        OptionSelection.this.setVisible(false);
    }//GEN-LAST:event_viewbookingsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        OptionSelection.this.setVisible(false);
        HomePage hp = new HomePage();
        hp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmtActionPerformed
        // TODO add your handling code here:
        OptionSelection.this.setVisible(false);

        HomePage hp = new HomePage();
        hp.setVisible(true);
    }//GEN-LAST:event_bmtActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bmt;
    private javax.swing.JLabel hello;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton newbooking;
    private javax.swing.JButton viewbookings;
    // End of variables declaration//GEN-END:variables
}
